### ISSUE TITLE
不知道为什么没办法加载sass

### ISSUE THREAD

**Issue by jiehua1995** [ZEROKISEKI/hexo-theme-gal#25]
```
$ hexo g
ERROR Plugin load failed: hexo-renderer-sass
Error: Missing binding F:\Workplace_Computer science\Workplace_Website\Hexo\node_modules\node-sass\vendor\win32-x64-64\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 10.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (F:\Workplace_Computer science\Workplace_Website\Hexo\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (F:\Workplace_Computer science\Workplace_Website\Hexo\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (F:\Workplace_Computer science\Workplace_Website\Hexo\node_modules\hexo-renderer-sass\lib\renderer.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (F:\Workplace_Computer science\Workplace_Website\Hexo\node_modules\hexo\lib\hexo\index.js:216:21)
    at F:\Workplace_Computer science\Workplace_Website\Hexo\node_modules\hexo-renderer-sass\index.js:4:20
    at F:\Workplace_Computer science\Workplace_Website\Hexo\node_modules\hexo\lib\hexo\index.js:232:12
    at tryCatcher (F:\Workplace_Computer science\Workplace_Website\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\Workplace_Computer science\Workplace_Website\Hexo\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (F:\Workplace_Computer science\Workplace_Website\Hexo\node_modules\bluebird\js\release\promise.js:569:18)
ERROR Plugin load failed: hexo-renderer-scss
Error: Missing binding F:\Workplace_Computer science\Workplace_Website\Hexo\node_modules\node-sass\vendor\win32-x64-64\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 10.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
```
似乎是说没办法binding
求大神们解释一下啊

**Comment by ZEROKISEKI** [comment]
升级了node版本之后最好重新安装下**node-sass**
```
npm install node-sass
```
如果不行的话，把Hexo目录下的**node_modules**文件夹删除后再重新**npm install**

**Comment by jiehua1995** [comment]
哦哦，好的，谢谢！！！最终解决方法是先升级node，然后yarn安装sass
