### ISSUE TITLE
hexo g 报错

### ISSUE THREAD

**Issue by rookiesmile** [ZEROKISEKI/hexo-theme-gal#3]
按照要求把需要的东西已经安装，但还是报错~
hexo g报错内容：

```
INFO  Start processing
INFO  Files loaded in 924 ms
Unhandled rejection TypeError: E:\Blog\themes\hexo-theme-gal-master\layout\layout.ejs:16
    14|                     <%- body %>
    15|                 </div>
 >> 16|                 <%- partial('_partial/sidebar') %>
    17|             </div>
    18|         </div>
    19|     </div>

E:\Blog\themes\hexo-theme-gal-master\layout\_partial\sidebar.ejs:3
    1| <aside class="col-md-4 gal-left" id="sidebar">
    2|     <%- partial('_widget/search') %>
 >> 3|     <%- partial('_widget/author') %>
    4|     <% if(theme.sidebar.recent_comments) { %>
    5|     <%- partial('_widget/recent_comments') %>
    6|     <% } %>

E:\Blog\themes\hexo-theme-gal-master\layout\_widget\author.ejs:11
    9|             <img src="<%- url_for(/https?:\/\//.test(theme.author_image) ? theme.author_image : `imgs/${theme.author_image}`) %>" width="140" height="140"
    10|                  alt="个人头像" class="author-image">
 >> 11|             <p class="author-description"><%- markdown(config.description) %></p>
    12|         </div>
    13|     </div>
    14| </aside>

No input file or string!
    at Render.renderSync (E:\Blog\node_modules\hexo\lib\hexo\render.js:86:27)
    at Object.render (E:\Blog\node_modules\hexo\lib\plugins\helper\render.js:5:23)
    at Object.wrapper [as render] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at Object.markdownHelper (E:\Blog\node_modules\hexo\lib\plugins\helper\markdown.js:4:15)
    at Object.wrapper [as markdown] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:31:150)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:31:231)
    at E:\Blog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:146)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:2536)
    at E:\Blog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:693)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:4472)
    at E:\Blog\node_modules\ejs\lib\ejs.js:255:15
Unhandled rejection TypeError: E:\Blog\themes\hexo-theme-gal-master\layout\layout.ejs:16
    14|                     <%- body %>
    15|                 </div>
 >> 16|                 <%- partial('_partial/sidebar') %>
    17|             </div>
    18|         </div>
    19|     </div>

E:\Blog\themes\hexo-theme-gal-master\layout\_partial\sidebar.ejs:3
    1| <aside class="col-md-4 gal-left" id="sidebar">
    2|     <%- partial('_widget/search') %>
 >> 3|     <%- partial('_widget/author') %>
    4|     <% if(theme.sidebar.recent_comments) { %>
    5|     <%- partial('_widget/recent_comments') %>
    6|     <% } %>

E:\Blog\themes\hexo-theme-gal-master\layout\_widget\author.ejs:11
    9|             <img src="<%- url_for(/https?:\/\//.test(theme.author_image) ? theme.author_image : `imgs/${theme.author_image}`) %>" width="140" height="140"
    10|                  alt="个人头像" class="author-image">
 >> 11|             <p class="author-description"><%- markdown(config.description) %></p>
    12|         </div>
    13|     </div>
    14| </aside>

No input file or string!
    at Render.renderSync (E:\Blog\node_modules\hexo\lib\hexo\render.js:86:27)
    at Object.render (E:\Blog\node_modules\hexo\lib\plugins\helper\render.js:5:23)
    at Object.wrapper [as render] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at Object.markdownHelper (E:\Blog\node_modules\hexo\lib\plugins\helper\markdown.js:4:15)
    at Object.wrapper [as markdown] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:31:150)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:31:231)
    at E:\Blog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:146)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:2536)
    at E:\Blog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:693)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:4472)
    at E:\Blog\node_modules\ejs\lib\ejs.js:255:15
Unhandled rejection TypeError: E:\Blog\themes\hexo-theme-gal-master\layout\layout.ejs:16
    14|                     <%- body %>
    15|                 </div>
 >> 16|                 <%- partial('_partial/sidebar') %>
    17|             </div>
    18|         </div>
    19|     </div>

E:\Blog\themes\hexo-theme-gal-master\layout\_partial\sidebar.ejs:3
    1| <aside class="col-md-4 gal-left" id="sidebar">
    2|     <%- partial('_widget/search') %>
 >> 3|     <%- partial('_widget/author') %>
    4|     <% if(theme.sidebar.recent_comments) { %>
    5|     <%- partial('_widget/recent_comments') %>
    6|     <% } %>

E:\Blog\themes\hexo-theme-gal-master\layout\_widget\author.ejs:11
    9|             <img src="<%- url_for(/https?:\/\//.test(theme.author_image) ? theme.author_image : `imgs/${theme.author_image}`) %>" width="140" height="140"
    10|                  alt="个人头像" class="author-image">
 >> 11|             <p class="author-description"><%- markdown(config.description) %></p>
    12|         </div>
    13|     </div>
    14| </aside>

No input file or string!
    at Render.renderSync (E:\Blog\node_modules\hexo\lib\hexo\render.js:86:27)
    at Object.render (E:\Blog\node_modules\hexo\lib\plugins\helper\render.js:5:23)
    at Object.wrapper [as render] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at Object.markdownHelper (E:\Blog\node_modules\hexo\lib\plugins\helper\markdown.js:4:15)
    at Object.wrapper [as markdown] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:31:150)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:31:231)
    at E:\Blog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:146)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:2536)
    at E:\Blog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:693)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:4472)
    at E:\Blog\node_modules\ejs\lib\ejs.js:255:15
Unhandled rejection TypeError: E:\Blog\themes\hexo-theme-gal-master\layout\layout.ejs:16
    14|                     <%- body %>
    15|                 </div>
 >> 16|                 <%- partial('_partial/sidebar') %>
    17|             </div>
    18|         </div>
    19|     </div>

E:\Blog\themes\hexo-theme-gal-master\layout\_partial\sidebar.ejs:3
    1| <aside class="col-md-4 gal-left" id="sidebar">
    2|     <%- partial('_widget/search') %>
 >> 3|     <%- partial('_widget/author') %>
    4|     <% if(theme.sidebar.recent_comments) { %>
    5|     <%- partial('_widget/recent_comments') %>
    6|     <% } %>

E:\Blog\themes\hexo-theme-gal-master\layout\_widget\author.ejs:11
    9|             <img src="<%- url_for(/https?:\/\//.test(theme.author_image) ? theme.author_image : `imgs/${theme.author_image}`) %>" width="140" height="140"
    10|                  alt="个人头像" class="author-image">
 >> 11|             <p class="author-description"><%- markdown(config.description) %></p>
    12|         </div>
    13|     </div>
    14| </aside>

No input file or string!
    at Render.renderSync (E:\Blog\node_modules\hexo\lib\hexo\render.js:86:27)
    at Object.render (E:\Blog\node_modules\hexo\lib\plugins\helper\render.js:5:23)
    at Object.wrapper [as render] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at Object.markdownHelper (E:\Blog\node_modules\hexo\lib\plugins\helper\markdown.js:4:15)
    at Object.wrapper [as markdown] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:31:150)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:31:231)
    at E:\Blog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:146)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:2536)
    at E:\Blog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:693)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:4472)
    at E:\Blog\node_modules\ejs\lib\ejs.js:255:15
Unhandled rejection TypeError: E:\Blog\themes\hexo-theme-gal-master\layout\layout.ejs:16
    14|                     <%- body %>
    15|                 </div>
 >> 16|                 <%- partial('_partial/sidebar') %>
    17|             </div>
    18|         </div>
    19|     </div>

E:\Blog\themes\hexo-theme-gal-master\layout\_partial\sidebar.ejs:3
    1| <aside class="col-md-4 gal-left" id="sidebar">
    2|     <%- partial('_widget/search') %>
 >> 3|     <%- partial('_widget/author') %>
    4|     <% if(theme.sidebar.recent_comments) { %>
    5|     <%- partial('_widget/recent_comments') %>
    6|     <% } %>

E:\Blog\themes\hexo-theme-gal-master\layout\_widget\author.ejs:11
    9|             <img src="<%- url_for(/https?:\/\//.test(theme.author_image) ? theme.author_image : `imgs/${theme.author_image}`) %>" width="140" height="140"
    10|                  alt="个人头像" class="author-image">
 >> 11|             <p class="author-description"><%- markdown(config.description) %></p>
    12|         </div>
    13|     </div>
    14| </aside>

No input file or string!
    at Render.renderSync (E:\Blog\node_modules\hexo\lib\hexo\render.js:86:27)
    at Object.render (E:\Blog\node_modules\hexo\lib\plugins\helper\render.js:5:23)
    at Object.wrapper [as render] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at Object.markdownHelper (E:\Blog\node_modules\hexo\lib\plugins\helper\markdown.js:4:15)
    at Object.wrapper [as markdown] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:31:150)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:31:231)
    at E:\Blog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:146)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:2536)
    at E:\Blog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (E:\Blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:693)
    at eval (eval at exports.compile (E:\Blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:4472)
    at E:\Blog\node_modules\ejs\lib\ejs.js:255:15
INFO  Generated: fonts/glyphicons-halflings-regular.ttf
INFO  Generated: fonts/glyphicons-halflings-regular.eot
INFO  Generated: fonts/glyphicons-halflings-regular.woff
INFO  Generated: fonts/glyphicons-halflings-regular.woff2
INFO  Generated: imgs/mouse1.cur
INFO  Generated: imgs/mouse2.cur
INFO  Generated: imgs/xsbg.gif
INFO  Generated: imgs/oni.mp3
INFO  Generated: imgs/oni/oni1.jpg
INFO  Generated: imgs/oni/oni2.jpg
INFO  Generated: imgs/oni/oni5.jpg
INFO  Generated: imgs/oni/oni3.jpg
INFO  Generated: imgs/oni/oni6.jpg
INFO  Generated: imgs/smilies/10.png
INFO  Generated: imgs/oni/oni4.jpg
INFO  Generated: imgs/smilies/11.png
INFO  Generated: imgs/smilies/1.png
INFO  Generated: imgs/smilies/12.png
INFO  Generated: imgs/smilies/13.png
INFO  Generated: imgs/smilies/14.png
INFO  Generated: imgs/smilies/16.png
INFO  Generated: imgs/smilies/15.png
INFO  Generated: imgs/smilies/18.png
INFO  Generated: imgs/smilies/17.png
INFO  Generated: imgs/smilies/19.png
INFO  Generated: imgs/smilies/20.png
INFO  Generated: imgs/smilies/22.png
INFO  Generated: imgs/smilies/21.png
INFO  Generated: imgs/smilies/23.png
INFO  Generated: imgs/smilies/25.png
INFO  Generated: imgs/smilies/24.png
INFO  Generated: imgs/smilies/4.png
INFO  Generated: imgs/smilies/3.png
INFO  Generated: imgs/smilies/8.png
INFO  Generated: imgs/smilies/7.png
INFO  Generated: imgs/smilies/9.png
INFO  Generated: imgs/smilies/5.png
INFO  Generated: js/highslide/graphics/close.png
INFO  Generated: imgs/smilies/6.png
INFO  Generated: js/highslide/graphics/closeX.png
INFO  Generated: js/highslide/graphics/controlbar-black-border.gif
INFO  Generated: js/highslide/graphics/controlbar-text-buttons.png
INFO  Generated: js/highslide/graphics/controlbar-white-small.gif
INFO  Generated: js/highslide/graphics/controlbar-white.gif
INFO  Generated: js/highslide/graphics/controlbar2.gif
INFO  Generated: js/highslide/graphics/controlbar3.gif
INFO  Generated: js/highslide/graphics/controlbar4-hover.gif
INFO  Generated: js/highslide/graphics/controlbar4.gif
INFO  Generated: js/highslide/graphics/geckodimmer.png
INFO  Generated: js/highslide/graphics/icon.gif
INFO  Generated: js/highslide/graphics/fullexpand.gif
INFO  Generated: js/highslide/graphics/loader.gif
INFO  Generated: js/highslide/graphics/resize.gif
INFO  Generated: js/highslide/graphics/scrollarrows.png
INFO  Generated: js/highslide/graphics/zoomin.cur
INFO  Generated: js/highslide/graphics/loader.white.gif
INFO  Generated: js/highslide/graphics/outlines/beveled.png
INFO  Generated: js/highslide/graphics/zoomout.cur
INFO  Generated: js/highslide/graphics/outlines/drop-shadow.png
INFO  Generated: imgs/smilies/2.png
INFO  Generated: js/highslide/graphics/outlines/glossy-dark.png
INFO  Generated: js/highslide/graphics/outlines/rounded-black.png
INFO  Generated: js/highslide/graphics/outlines/rounded-white.png
INFO  Generated: fonts/fontawesome-webfont.woff
INFO  Generated: fonts/fontawesome-webfont.woff2
INFO  Generated: fonts/glyphicons-halflings-regular.svg
INFO  Generated: imgs/avatar.jpg
INFO  Generated: imgs/slide/background2.jpg
INFO  Generated: js/highslide/graphics/outlines/outer-glow.png
INFO  Generated: js/bootstrap-hover-dropdown.min.js
INFO  Generated: js/activate-power-mode.js
INFO  Generated: js/aos.js
INFO  Generated: js/oni.js
INFO  Generated: js/comment/leancloud.js
INFO  Generated: js/highslide/highslide.css
INFO  Generated: css/aos.css
INFO  Generated: js/bootstrap.min.js
INFO  Generated: js/hs.js
INFO  Generated: js/jquery.min.js
INFO  Generated: css/bootstrap.min.css
INFO  Generated: js/comment/gitment.js
INFO  Generated: js/highslide/highslide-full.packed.js
INFO  Generated: js/highslide/highslide-with-gallery.packed.js
INFO  Generated: js/highslide/highslide-with-html.min.js
INFO  Generated: js/highslide/highslide-with-html.packed.js
INFO  Generated: js/highslide/highslide.js
INFO  Generated: js/highslide/highslide.min.js
INFO  Generated: js/highslide/highslide.packed.js
INFO  Generated: js/highslide/highslide-with-gallery.min.js
INFO  Generated: js/highslide/highslide-full.js
INFO  Generated: js/highslide/highslide-full.min.js
INFO  Generated: js/highslide/highslide-with-gallery.js
INFO  Generated: js/highslide/highslide-with-html.js
INFO  Generated: imgs/slide/background5.jpg
INFO  Generated: fonts/FontAwesome.otf
INFO  Generated: fonts/fontawesome-webfont.eot
INFO  Generated: fonts/fontawesome-webfont.ttf
INFO  Generated: imgs/slide/background4.jpg
INFO  Generated: js/blog.js
INFO  Generated: js/highslide/highslide-ie6.css
INFO  Generated: js/highslide/graphics/outlines/Outlines.psd
INFO  Generated: imgs/slide/background3.jpg
INFO  Generated: imgs/preview/preview1.jpg
INFO  Generated: imgs/preview/preview4.jpg
INFO  Generated: imgs/preview/preview2.jpg
INFO  Generated: imgs/slide/background6.jpg
INFO  Generated: imgs/preview/preview3.jpg
INFO  Generated: fonts/fontawesome-webfont.svg
INFO  Generated: imgs/slide/background1.jpg
INFO  Generated: css/style.css
```

**Comment by ZEROKISEKI** [comment]
把站点目录的`_config.yml`(不是主题目录下的`_config.yml`)的description配置一下应该就行了, 比如我的:

```

# Site
title: 喵绪～
subtitle:
description: にひひ~~
author: AONOSORA
language:
timezone:# Hexo Configuration

```

**Comment by rookiesmile** [comment]
FATAL can not read a block mapping entry; a multiline key may not be an implicit key at line 13, column 1:
    # URL
    ^
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 13, column 1:
    # URL
    ^
    at generateError (E:\Blog\node_modules\js-yaml\lib\js-yaml\loader.js:165:10)
    at throwError (E:\Blog\node_modules\js-yaml\lib\js-yaml\loader.js:171:9)
    at readBlockMapping (E:\Blog\node_modules\js-yaml\lib\js-yaml\loader.js:1046:9)
    at composeNode (E:\Blog\node_modules\js-yaml\lib\js-yaml\loader.js:1332:12)
    at readDocument (E:\Blog\node_modules\js-yaml\lib\js-yaml\loader.js:1492:3)
    at loadDocuments (E:\Blog\node_modules\js-yaml\lib\js-yaml\loader.js:1548:5)
    at Object.load (E:\Blog\node_modules\js-yaml\lib\js-yaml\loader.js:1569:19)
    at Hexo.yamlHelper (E:\Blog\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\Blog\node_modules\bluebird\js\release\method.js:15:34)
    at E:\Blog\node_modules\hexo\lib\hexo\render.js:61:21
    at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\Blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\Blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\Blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)

**Comment by ZEROKISEKI** [comment]
格式不对， 比如需要空格隔开的地方，你却少了空格。`:`后面要有个空格, 比如`description: 测试`,

**Comment by rookiesmile** [comment]
问题解决！谢谢！很喜欢这个主题的风格！加油完善！

**Comment by pheromone** [comment]
@rookiesmile  我的也是这个错误,请问你是怎么解决的,我添加了
# Site
title: aaaa
subtitle:
description: ddd
author: ffff
language: 
timezone:# Hexo Configuration
也还会报错啊

**Comment by ZEROKISEKI** [comment]
@pheromone 你试试把timezone的内容加个空格或者去掉

title: aaaa
subtitle:
description: ddd
author: ffff
language: 
timezone:
