### ISSUE TITLE
求助！代码报错了.

### ISSUE THREAD

**Issue by SimpleIcomputer** [ZEROKISEKI/hexo-theme-gal#31]
好像不怎么影响使用.   完整报错信息：
TypeError: /home/coding/workspace/web/themes/gal/layout/index.ejs:18
    16|             <% })
    17|         } %>
 >> 18|      <% page.posts.filter(function (post) {
    19|          return typeof post.top === 'undefined' || post.top === false
    20|      }).forEach(function (post) { %>
    21|      <%- partial('_partial/excerpt', { item: post }) %>

Cannot read property 'filter' of undefined
    at eval (eval at compile (/home/coding/workspace/web/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:39:18)
    at returnedFn (/home/coding/workspace/web/node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (/home/coding/workspace/web/node_modules/hexo/lib/theme/view.js:124:48)
    at Theme._View.View.View.render (/home/coding/workspace/web/node_modules/hexo/lib/theme/view.js:29:15)
    at route.set (/home/coding/workspace/web/node_modules/hexo/lib/hexo/index.js:386:29)
    at tryCatcher (/home/coding/workspace/web/node_modules/bluebird/js/release/util.js:16:23)
    at /home/coding/workspace/web/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/coding/workspace/web/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:445:10)
    at resume_ (_stream_readable.js:825:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by ZEROKISEKI** [comment]
可能是你的hexo版本比较老了，可以试着更新hexo版本之后再尝试
